### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by CalvinDKL** [MastaCoder/MyUsers#7]
Hello, when i try to install it i get an error.
This is how i set it up.
https://gyazo.com/797784f81350295b81ef9e1164fe33e4
This is the error.
https://gyazo.com/d60c6ad9608939505eb22ea55f7071a1

**Comment by makandz** [comment]
Connection isn't valid, or try a reinstalled copy of it. Check the database to make sure it hasn't written to it yet and it's all blank.

This project is currently dead, might update it later with more supporting features.
